import SwiftUI
import SwiftRender

/// BillionDollars — an animated, narrated explainer of Paul Graham's essay
/// "How to Earn a Billion Dollars" (June 2026).
///
/// Fourteen chapters on a shared `anchors` grid. Each chapter is a pure
/// function of local time that *illustrates* a beat of the argument — the
/// 93%-a-month founder, log(500, 1.93) ≈ 9.45, 1.15^60 ≈ 4384, the two
/// numbers, "ideas sound lame", Justin.TV → Twitch — rather than just
/// captioning it. A synthesized ambient score is declared next to the same
/// `anchors` array, so music can't drift from picture.
///
/// Kokoro TTS narration is layered on at render time — `durs` below is
/// generated from the measured VO length by `tools/billion_vo.py`, and the
/// VO start times mirror `anchors`. One command does the whole pipeline:
///
///   bash tools/make_billion_audio.sh        # Kokoro VO → mix → render
///   swift run swift-render render BillionDollars --out out/billion.mp4   # silent picture + score
public struct BillionDollars: RenderScene {
    // 14 chapter lengths (s). GENERATED by tools/billion_vo.py — keep in sync.
    static let durs: [Double] = [6.2, 13.2, 17.3, 14.2, 20.5, 18.4, 16, 17.2, 11.8, 15.2, 16.6, 14.9, 12.6, 13.7]
    static let cross: Double = 0.5   // crossfade overlap between chapters

    /// Absolute start of each chapter. anchors[i+1] = anchors[i] + durs[i] - cross.
    static let anchors: [Double] = {
        var out: [Double] = []; var c = 0.0
        for d in durs { out.append(c); c += d - cross }
        return out
    }()

    public static let defaultDuration: Double = anchors.last! + durs.last!   // ≈ 201.3s

    // MARK: palette
    static let bg     = Color(red: 0.039, green: 0.039, blue: 0.047)
    static let ink    = Color(red: 0.961, green: 0.949, blue: 0.925)
    static let dim    = Color(red: 0.56,  green: 0.57,  blue: 0.60)
    static let faint  = Color(red: 0.30,  green: 0.31,  blue: 0.34)
    static let accent = Color(red: 0.776, green: 1.0,   blue: 0.102)   // #C7FF1A volt
    static let gold   = Color(red: 1.0,   green: 0.784, blue: 0.341)   // #FFC857 money
    static let warn   = Color(red: 0.949, green: 0.471, blue: 0.361)   // #F2785C
    static let panel  = Color(white: 0.075)

    // MARK: - Body

    @MainActor public static func body(at t: Double, duration: Double) -> some View {
        let a = anchors
        return ZStack {
            bg.ignoresSafeArea()
            Timeline(t) {
                Clip(at: a[0],  for: durs[0])  { l in wrap(l, durs[0])  { titleCard(l) } }
                Clip(at: a[1],  for: durs[1])  { l in wrap(l, durs[1])  { theClaim(l) } }
                Clip(at: a[2],  for: durs[2])  { l in wrap(l, durs[2])  { theFounder(l) } }
                Clip(at: a[3],  for: durs[3])  { l in wrap(l, durs[3])  { theObjection(l) } }
                Clip(at: a[4],  for: durs[4])  { l in wrap(l, durs[4])  { calcLog(l) } }
                Clip(at: a[5],  for: durs[5])  { l in wrap(l, durs[5])  { calcCompound(l) } }
                Clip(at: a[6],  for: durs[6])  { l in wrap(l, durs[6])  { exponentialMagic(l) } }
                Clip(at: a[7],  for: durs[7])  { l in wrap(l, durs[7])  { twoNumbers(l) } }
                Clip(at: a[8],  for: durs[8])  { l in wrap(l, durs[8])  { tellFriends(l) } }
                Clip(at: a[9],  for: durs[9])  { l in wrap(l, durs[9])  { predictDemand(l) } }
                Clip(at: a[10], for: durs[10]) { l in wrap(l, durs[10]) { ideasSoundLame(l) } }
                Clip(at: a[11], for: durs[11]) { l in wrap(l, durs[11]) { twitch(l) } }
                Clip(at: a[12], for: durs[12]) { l in wrap(l, durs[12]) { empathy(l) } }
                Clip(at: a[13], for: durs[13]) { l in wrap(l, durs[13]) { lockup(l) } }
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    /// Score lives next to the Timeline: `anchors` drives both cuts and hits.
    public static func soundtrack(duration: Double) -> Score? {
        let cuts = Array(anchors.dropFirst())
        return Score(duration: duration) {
            drone(.a1, from: 0, for: duration, amp: 0.075)
            drone(.e2, from: anchors[6], for: 95, amp: 0.03)
            boom(at: 0.2, amp: 0.45, duration: 2.4)
            crashes(at: cuts, amp: 0.11)
            // calc reveals — a hit lands when the number lands
            boom(at: anchors[4] + 10.6,  amp: 0.4, duration: 2.0)     // log(500,1.93) ≈ 9.45
            boom(at: anchors[5] + 9.8,   amp: 0.4, duration: 2.0)     // ×4384
            // momentum into the thesis slide
            every(1.0, from: anchors[7], to: anchors[7] + 6) { kick(at: $0, amp: 0.2) }
            boom(at: anchors[13], amp: 0.7, duration: 3.0)            // lockup finale
        }
    }


    // MARK: - Shared building blocks

    /// Per-chapter crossfade: up over the first `cross`, down over the last.
    @ViewBuilder @MainActor
    static func wrap<V: View>(_ l: Double, _ dur: Double, @ViewBuilder _ content: () -> V) -> some View {
        let fin = Ease.easeInOut(Ease.clip(l, 0, cross))
        let fout = 1 - Ease.easeInOut(Ease.clip(l, dur - cross, dur))
        content()
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .opacity(fin * fout)
    }

    /// Small mono uppercase kicker label with an accent tick.
    @ViewBuilder
    static func kicker(_ text: String, _ p: Double, color: Color = accent) -> some View {
        HStack(spacing: 12) {
            Rectangle().fill(color).frame(width: 22, height: 3)
            Text(text)
                .font(.system(size: 22, weight: .semibold, design: .monospaced))
                .tracking(4)
                .foregroundStyle(color)
        }
        .opacity(p)
        .offset(x: (1 - p) * -24)
    }

    /// A line that wipes up behind a moving mask.
    @ViewBuilder
    static func reveal<V: View>(_ p: Double, height: CGFloat, @ViewBuilder _ content: () -> V) -> some View {
        content()
            .opacity(p)
            .mask(Rectangle().frame(height: CGFloat(p) * height).frame(maxHeight: .infinity, alignment: .top))
    }

    /// Marker orbiting the center of a 2R box at `angleDeg`.
    @ViewBuilder
    static func orbit<V: View>(radius R: CGFloat, angleDeg: Double, @ViewBuilder _ child: () -> V) -> some View {
        ZStack { child().offset(x: R) }
            .frame(width: 2 * R, height: 2 * R)
            .rotationEffect(.degrees(angleDeg))
    }

    /// Exponential curve from (0,h) climbing to the top-right, drawn 0→p.
    @ViewBuilder
    static func expCurve(_ p: Double, w: CGFloat, h: CGFloat, k: Double,
                         color: Color, lineWidth: CGFloat = 5) -> some View {
        let maxY = exp(k) - 1
        Path { path in
            path.move(to: CGPoint(x: 0, y: h))
            let n = 150
            for i in 0...n {
                let x = Double(i) / Double(n)
                let yy = (exp(k * x) - 1) / maxY            // 0…1
                path.addLine(to: CGPoint(x: CGFloat(x) * w, y: h - CGFloat(yy) * h))
            }
        }
        .trim(from: 0, to: p)
        .stroke(color, style: StrokeStyle(lineWidth: lineWidth, lineCap: .round, lineJoin: .round))
        .frame(width: w, height: h)
    }

    static func hash01(_ x: Double) -> Double {
        abs((sin(x) * 43758.5453).truncatingRemainder(dividingBy: 1.0))
    }

    // MARK: - 00 · Title

    @MainActor static func titleCard(_ t: Double) -> some View {
        let glow = Ease.easeOut(Ease.clip(t, 0.0, 2.2))
        let k    = Ease.easeOut(Ease.clip(t, 0.2, 0.9))
        let l1   = Ease.easeOut(Ease.clip(t, 0.5, 1.4))
        let l2   = Ease.easeOut(Ease.clip(t, 0.9, 1.8))
        let line = Ease.easeInOut(Ease.clip(t, 1.6, 2.5))
        let sub  = Ease.easeOut(Ease.clip(t, 2.3, 3.2))
        return ZStack {
            Rectangle().fill(.black)
                .colorEffect(ShaderLibrary.swiftRender.plasmaField(
                    .float2(1920, 1080), .float(Float(t * 0.5)), .float(1.5)))
                .opacity(glow * 0.20)
                .ignoresSafeArea()
            VStack(alignment: .leading, spacing: 0) {
                kicker("PAUL GRAHAM · OXFORD UNION · JUNE 2026", k)
                    .padding(.bottom, 30)
                reveal(l1, height: 180) {
                    Text("How to earn a")
                        .font(.custom("Inter-Black", size: 138)).tracking(-5)
                        .foregroundStyle(ink)
                }
                reveal(l2, height: 180) {
                    HStack(spacing: 0) {
                        Text("billion ").font(.custom("Inter-Black", size: 138)).tracking(-5).foregroundStyle(ink)
                        Text("dollars.").font(.custom("Inter-Black", size: 138)).tracking(-5).foregroundStyle(gold)
                    }
                }
                Rectangle().fill(accent)
                    .frame(width: CGFloat(line) * 560, height: 8)
                    .padding(.top, 22).padding(.bottom, 26)
                Text("hard, but possible — and it's only two numbers.")
                    .font(.custom("Inter-Light", size: 44)).tracking(-0.5)
                    .foregroundStyle(dim)
                    .opacity(sub).offset(y: (1 - sub) * 16)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, 160)
        }
    }

    // MARK: - 01 · The claim

    @MainActor static func theClaim(_ t: Double) -> some View {
        let k     = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let q     = Ease.easeOut(Ease.clip(t, 0.7, 1.8))
        let strike = Ease.easeInOut(Ease.clip(t, 3.2, 4.4))      // cross out "impossible"
        let rebut = Ease.easeOutBack(Ease.clip(t, 4.6, 5.6))
        let stats = Ease.easeOut(Ease.clip(t, 6.2, 7.2))
        return ZStack {
            VStack(alignment: .leading, spacing: 40) {
                kicker("THE CLAIM", k, color: warn)
                VStack(alignment: .leading, spacing: 6) {
                    Text("“It's impossible to earn")
                        .font(.custom("Inter-Light", size: 64)).foregroundStyle(dim)
                    ZStack(alignment: .leading) {
                        Text("a billion dollars.”")
                            .font(.custom("Inter-Bold", size: 92)).tracking(-2).foregroundStyle(ink)
                        Rectangle().fill(warn)
                            .frame(width: CGFloat(strike) * 690, height: 7)
                            .offset(y: 4)
                    }
                }
                .opacity(q)
                Text("hard — but possible.")
                    .font(.custom("Inter-Black", size: 70)).tracking(-1.5).foregroundStyle(accent)
                    .opacity(rebut).scaleEffect(0.85 + 0.15 * rebut, anchor: .leading)
                HStack(spacing: 46) {
                    statChip("21", "YEARS COACHING FOUNDERS")
                    statChip("~6,500", "STARTUPS FUNDED")
                    statChip("~30", "BECAME BILLIONAIRES")
                }
                .opacity(stats).offset(y: (1 - stats) * 20)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, 160)
        }
    }

    @ViewBuilder static func statChip(_ n: String, _ label: String) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(n).font(.custom("Inter-Black", size: 56)).foregroundStyle(gold)
            Text(label).font(.system(size: 18, weight: .semibold, design: .monospaced))
                .tracking(2).foregroundStyle(dim)
        }
    }

    // MARK: - 02 · The 93% founder

    @MainActor static func theFounder(_ t: Double) -> some View {
        let k      = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let count  = Ease.easeOut(Ease.clip(t, 1.0, 3.2))
        let curveP = Ease.easeInOut(Ease.clip(t, 1.4, 6.0))
        let netP   = Ease.easeOut(Ease.clip(t, 6.5, 7.4))
        let cap    = Ease.easeOut(Ease.clip(t, 9.5, 10.6))
        let pct = Int(round(count * 93))
        let w: CGFloat = 760, h: CGFloat = 360
        return ZStack {
            kicker("ONE FOUNDER · LAST MONTH", k)
                .frame(maxHeight: .infinity, alignment: .top).padding(.top, 120)
            HStack(spacing: 90) {
                VStack(alignment: .leading, spacing: 2) {
                    HStack(alignment: .firstTextBaseline, spacing: 4) {
                        Text("\(pct)").font(.custom("Inter-Black", size: 200)).foregroundStyle(accent)
                        Text("%").font(.custom("Inter-Black", size: 110)).foregroundStyle(accent)
                    }
                    Text("growth — per month")
                        .font(.custom("Inter-Light", size: 38)).foregroundStyle(dim)
                    Text("so her net worth grew 93%/mo too")
                        .font(.custom("Inter-Medium", size: 30)).foregroundStyle(gold)
                        .opacity(netP).offset(y: (1 - netP) * 14).padding(.top, 14)
                }
                ZStack(alignment: .bottomLeading) {
                    // baseline + curve
                    Rectangle().fill(faint).frame(width: w, height: 2)
                        .frame(width: w, height: h, alignment: .bottom)
                    expCurve(curveP, w: w, h: h, k: 3.4, color: accent, lineWidth: 6)
                    Circle().fill(ink).frame(width: 20, height: 20)
                        .shadow(color: accent.opacity(0.9), radius: 14)
                        .position(x: CGFloat(curveP) * w,
                                  y: h - CGFloat((exp(3.4 * curveP) - 1) / (exp(3.4) - 1)) * h)
                        .opacity(curveP > 0.02 ? 1 : 0)
                }
                .frame(width: w, height: h)
            }
            Text("she wasn't exploiting anyone — users loved it, and told their friends.")
                .font(.custom("Inter-Medium", size: 36)).foregroundStyle(ink)
                .opacity(cap)
                .frame(maxHeight: .infinity, alignment: .bottom).padding(.bottom, 120)
        }
    }

    // MARK: - 03 · The objection

    @MainActor static func theObjection(_ t: Double) -> some View {
        let k   = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let lp  = Ease.spring(t, from: -460, to: 0, response: 0.7, dampingFraction: 0.8)
        let rp  = Ease.spring(t, from: 460, to: 0, response: 0.7, dampingFraction: 0.8)
        let neq = Ease.easeOutBack(Ease.clip(t, 1.6, 2.4))
        let tease = Ease.easeOut(Ease.clip(t, 8.4, 9.6))
        return ZStack {
            kicker("THE OBJECTION", k, color: dim)
                .frame(maxHeight: .infinity, alignment: .top).padding(.top, 130)
            HStack(spacing: 0) {
                amountCard("a few million", "$2,000,000", gold).offset(x: lp)
                VStack(spacing: 8) {
                    Text("≠").font(.custom("Inter-Light", size: 120)).foregroundStyle(warn)
                    Text("\"radically\ndifferent\"").multilineTextAlignment(.center)
                        .font(.system(size: 22, weight: .semibold, design: .monospaced))
                        .foregroundStyle(dim)
                }
                .opacity(neq).scaleEffect(0.6 + 0.4 * neq).frame(width: 260)
                amountCard("a billion", "$1,000,000,000", gold).offset(x: rp)
            }
            Text("…or is it? Let's do the math.")
                .font(.custom("Inter-Medium", size: 40)).foregroundStyle(accent)
                .opacity(tease)
                .frame(maxHeight: .infinity, alignment: .bottom).padding(.bottom, 130)
        }
    }

    @ViewBuilder static func amountCard(_ title: String, _ value: String, _ color: Color) -> some View {
        VStack(spacing: 14) {
            Text(title).font(.custom("Inter-Light", size: 34)).foregroundStyle(dim)
            Text(value).font(.custom("Inter-Black", size: 56)).tracking(-1).foregroundStyle(color)
        }
        .padding(.vertical, 46).frame(width: 540)
        .background(RoundedRectangle(cornerRadius: 26, style: .continuous).fill(panel))
        .overlay(RoundedRectangle(cornerRadius: 26, style: .continuous).stroke(color.opacity(0.35), lineWidth: 1.5))
    }

    // MARK: - 04 · log(500, 1.93) ≈ 9.45  (the money shot)

    @MainActor static func calcLog(_ t: Double) -> some View {
        let k     = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let mult  = Ease.easeOutBack(Ease.clip(t, 1.2, 2.2))
        let typeP = Ease.clip(t, 3.2, 6.2)                       // search box types the formula
        let formula = "log(500, 1.93)"
        let typed = Int(round(typeP * Double(formula.count)))
        let shown = String(formula.prefix(typed))
        let caret = typeP < 1 ? "▌" : ""
        let resP  = Ease.easeOutBack(Ease.clip(t, 9.6, 10.8))    // = 9.45
        let lineP = Ease.easeInOut(Ease.clip(t, 12.2, 14.0))     // number line draws
        let apart = Ease.easeOut(Ease.clip(t, 14.6, 15.8))
        return ZStack {
            kicker("THE CALCULATION", k)
                .frame(maxHeight: .infinity, alignment: .top).padding(.top, 90)
            VStack(spacing: 34) {
                Text("$2M → $1B  is  500× growth")
                    .font(.custom("Inter-Medium", size: 40)).foregroundStyle(gold)
                    .opacity(mult).scaleEffect(0.9 + 0.1 * mult)

                // search-box styled formula
                HStack(spacing: 18) {
                    Image(systemName: "magnifyingglass")
                        .font(.system(size: 30, weight: .medium)).foregroundStyle(dim)
                    Text(shown + caret)
                        .font(.system(size: 44, weight: .semibold, design: .monospaced))
                        .foregroundStyle(ink)
                    Spacer(minLength: 0)
                }
                .padding(.horizontal, 36).padding(.vertical, 26).frame(width: 760)
                .background(Capsule().fill(Color(white: 0.10)))
                .overlay(Capsule().stroke(faint, lineWidth: 1.5))

                HStack(spacing: 18) {
                    Text("=").font(.custom("Inter-Light", size: 72)).foregroundStyle(dim)
                    Text("9.45").font(.custom("Inter-Black", size: 110)).foregroundStyle(accent)
                    Text("months").font(.custom("Inter-Light", size: 44)).foregroundStyle(ink)
                }
                .opacity(resP).scaleEffect(0.8 + 0.2 * resP)

                // number line: $2M ●———————● $1B
                ZStack {
                    Rectangle().fill(accent)
                        .frame(width: CGFloat(lineP) * 900, height: 4)
                        .frame(width: 900, alignment: .leading)
                    HStack {
                        endDot("$2M")
                        Spacer()
                        endDot("$1B")
                    }
                    .frame(width: 900)
                    Text("9½ MONTHS APART")
                        .font(.system(size: 22, weight: .heavy, design: .monospaced)).tracking(3)
                        .foregroundStyle(gold)
                        .padding(.horizontal, 18).padding(.vertical, 8)
                        .background(Capsule().fill(bg))
                        .overlay(Capsule().stroke(gold.opacity(0.5), lineWidth: 1))
                        .opacity(apart).offset(y: -42)
                }
                .frame(width: 900, height: 90).padding(.top, 8)
            }
        }
    }

    @ViewBuilder static func endDot(_ label: String) -> some View {
        VStack(spacing: 10) {
            Text(label).font(.custom("Inter-Bold", size: 32)).foregroundStyle(gold)
            Circle().fill(accent).frame(width: 22, height: 22)
                .shadow(color: accent.opacity(0.8), radius: 8)
        }
    }

    // MARK: - 05 · 1.15^60 ≈ 4384

    @MainActor static func calcCompound(_ t: Double) -> some View {
        let k     = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let rateP = Ease.easeOutBack(Ease.clip(t, 0.8, 1.6))
        let curveP = Ease.easeInOut(Ease.clip(t, 1.8, 8.0))
        let count = Ease.easeOut(Ease.clip(t, 6.0, 9.6))
        let mult = Int(round(count * 4384))
        let by30 = Ease.easeOutBack(Ease.clip(t, 11.0, 12.2))
        let w: CGFloat = 980, h: CGFloat = 380
        return ZStack {
            kicker("EVEN AT A CALMER 15% / MONTH", k)
                .frame(maxHeight: .infinity, alignment: .top).padding(.top, 95)
            VStack(spacing: 22) {
                Text("15% / month")
                    .font(.custom("Inter-Black", size: 64)).foregroundStyle(accent)
                    .opacity(rateP).scaleEffect(0.85 + 0.15 * rateP)
                ZStack(alignment: .bottomLeading) {
                    Rectangle().fill(faint).frame(width: w, height: 2)
                        .frame(width: w, height: h, alignment: .bottom)
                    expCurve(curveP, w: w, h: h, k: 4.2, color: gold, lineWidth: 6)
                    // x-axis labels
                    HStack { Text("0").foregroundStyle(dim); Spacer(); Text("60 months").foregroundStyle(dim) }
                        .font(.system(size: 22, design: .monospaced))
                        .frame(width: w).offset(y: 28)
                }
                .frame(width: w, height: h)
                HStack(spacing: 24) {
                    Text("1.15⁶⁰  ≈")
                        .font(.system(size: 44, weight: .semibold, design: .monospaced)).foregroundStyle(dim)
                    Text("×\(mult)")
                        .font(.custom("Inter-Black", size: 88)).foregroundStyle(ink)
                    Text("billionaire by 30")
                        .font(.custom("Inter-Bold", size: 36)).foregroundStyle(accent)
                        .padding(.horizontal, 22).padding(.vertical, 12)
                        .background(Capsule().stroke(accent.opacity(0.5), lineWidth: 1.5))
                        .opacity(by30).scaleEffect(0.85 + 0.15 * by30)
                }
            }
        }
    }

    // MARK: - 06 · Exponential growth is like magic

    @MainActor static func exponentialMagic(_ t: Double) -> some View {
        let k     = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let flat  = Ease.easeInOut(Ease.clip(t, 0.9, 2.2))      // the "linear intuition" line
        let curveP = Ease.easeInOut(Ease.clip(t, 2.2, 6.5))
        let title = Ease.easeOutBack(Ease.clip(t, 3.0, 4.0))
        let cap   = Ease.easeOut(Ease.clip(t, 9.5, 10.8))
        let w: CGFloat = 1300, h: CGFloat = 560
        return ZStack {
            Rectangle().fill(.black)
                .colorEffect(ShaderLibrary.swiftRender.galaxy(.float2(1920, 1080), .float(Float(t * 0.4))))
                .opacity(0.14 * Ease.easeOut(Ease.clip(t, 0.3, 1.6)))
                .ignoresSafeArea()
            kicker("WHY THEY DON'T BELIEVE IT", k, color: dim)
                .frame(maxHeight: .infinity, alignment: .top).padding(.top, 100)
            ZStack(alignment: .bottomLeading) {
                // flat "what people expect"
                Rectangle().fill(faint)
                    .frame(width: CGFloat(flat) * w, height: 3)
                    .frame(width: w, height: h, alignment: .bottomLeading)
                    .offset(y: -60)
                Text("linear intuition")
                    .font(.system(size: 22, design: .monospaced)).foregroundStyle(faint)
                    .opacity(flat).frame(width: w, height: h, alignment: .bottomLeading)
                    .offset(x: 12, y: -78)
                // the exponential reality blowing off the top
                expCurve(curveP, w: w, h: h, k: 5.0, color: accent, lineWidth: 7)
                Circle().fill(ink).frame(width: 24, height: 24)
                    .shadow(color: accent.opacity(0.9), radius: 22)
                    .position(x: CGFloat(curveP) * w,
                              y: h - CGFloat((exp(5.0 * curveP) - 1) / (exp(5.0) - 1)) * h)
                    .opacity(curveP > 0.02 ? 1 : 0)
            }
            .frame(width: w, height: h)
            VStack(spacing: 14) {
                Text("exponential growth is like magic")
                    .font(.custom("Inter-Black", size: 76)).tracking(-2).foregroundStyle(ink)
                    .scaleEffect(0.9 + 0.1 * title).opacity(title)
                Text("it looks impossible — so they assume you cheated")
                    .font(.custom("Inter-Light", size: 34)).foregroundStyle(dim).opacity(cap)
            }
            .frame(maxHeight: .infinity, alignment: .top).padding(.top, 210)
        }
    }

    // MARK: - 07 · The two numbers (thesis)

    @MainActor static func twoNumbers(_ t: Double) -> some View {
        let k    = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let lp   = Ease.spring(t, from: -440, to: 0, response: 0.7, dampingFraction: 0.78)
        let rp   = Ease.spring(t, from: 440, to: 0, response: 0.7, dampingFraction: 0.78)
        let times = Ease.easeOutBack(Ease.clip(t, 1.3, 2.0))
        let eq   = Ease.easeOut(Ease.clip(t, 3.2, 4.0))
        let res  = Ease.easeOutBack(Ease.clip(t, 4.0, 5.0))
        return ZStack {
            kicker("THERE ARE ONLY TWO NUMBERS", k)
                .frame(maxHeight: .infinity, alignment: .top).padding(.top, 95)
            VStack(spacing: 40) {
                HStack(spacing: 0) {
                    factorCard("GROWTH RATE", "make something people\ntell their friends about", "honest — startups do it all the time", accent)
                        .offset(x: lp)
                    Text("×").font(.custom("Inter-Light", size: 110)).foregroundStyle(ink)
                        .opacity(times).scaleEffect(0.5 + 0.5 * times).frame(width: 150)
                    factorCard("HOW LONG IT LASTS", "the size of your\nmarket", "cheating can't make a market bigger", gold)
                        .offset(x: rp)
                }
                HStack(spacing: 22) {
                    Text("=").font(.custom("Inter-Light", size: 80)).foregroundStyle(dim).opacity(eq)
                    Text("$1,000,000,000")
                        .font(.custom("Inter-Black", size: 84)).tracking(-2).foregroundStyle(ink)
                        .opacity(res).scaleEffect(0.85 + 0.15 * res)
                }
            }
            .padding(.horizontal, 110)
        }
    }

    @ViewBuilder static func factorCard(_ title: String, _ how: String, _ note: String, _ color: Color) -> some View {
        VStack(alignment: .leading, spacing: 16) {
            Text(title).font(.custom("Inter-Black", size: 46)).tracking(-1).foregroundStyle(color)
            Rectangle().fill(color.opacity(0.5)).frame(height: 2)
            Text(how).font(.custom("Inter-Medium", size: 32)).foregroundStyle(ink)
                .fixedSize(horizontal: false, vertical: true).lineSpacing(4)
            Spacer(minLength: 0)
            Text(note).font(.system(size: 21, weight: .semibold, design: .monospaced))
                .foregroundStyle(dim).fixedSize(horizontal: false, vertical: true).lineSpacing(3)
        }
        .padding(36)
        .frame(width: 600, height: 380, alignment: .topLeading)
        .background(RoundedRectangle(cornerRadius: 28, style: .continuous).fill(panel))
        .overlay(RoundedRectangle(cornerRadius: 28, style: .continuous).stroke(color.opacity(0.35), lineWidth: 1.5))
    }

    // MARK: - 08 · Tell their friends (viral spread)

    @MainActor static func tellFriends(_ t: Double) -> some View {
        let k = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let cap = Ease.easeOut(Ease.clip(t, 7.4, 8.6))
        return ZStack {
            kicker("HOW YOU GET THE GROWTH RATE", k)
                .frame(maxHeight: .infinity, alignment: .top).padding(.top, 120)
            // three generations of branching dots
            ZStack {
                spreadNode(t, gen: 0, idx: 0, count: 1, start: 0.7)
                ForEach(0..<3, id: \.self) { i in spreadNode(t, gen: 1, idx: i, count: 3, start: 1.6) }
                ForEach(0..<9, id: \.self) { i in spreadNode(t, gen: 2, idx: i, count: 9, start: 2.8) }
            }
            .frame(width: 1400, height: 560)
            Text("make something so good they tell their friends")
                .font(.custom("Inter-Bold", size: 46)).foregroundStyle(ink)
                .opacity(cap)
                .frame(maxHeight: .infinity, alignment: .bottom).padding(.bottom, 110)
        }
    }

    @ViewBuilder static func spreadNode(_ t: Double, gen: Int, idx: Int, count: Int, start: Double) -> some View {
        let p = Ease.easeOutBack(Ease.clip(t, start + Double(idx) * 0.05, start + 0.5 + Double(idx) * 0.05))
        let y = CGFloat(gen) * 180 - 180
        let spanW: CGFloat = gen == 0 ? 0 : (gen == 1 ? 760 : 1240)
        let x = count == 1 ? 0 : (CGFloat(idx) / CGFloat(count - 1) - 0.5) * spanW
        let c = gen == 0 ? Self.accent : (gen == 1 ? Self.ink : Self.dim)
        let size: CGFloat = gen == 0 ? 46 : (gen == 1 ? 30 : 20)
        Circle().fill(c).frame(width: size, height: size)
            .shadow(color: c.opacity(0.6), radius: gen == 0 ? 16 : 6)
            .scaleEffect(p).opacity(p)
            .offset(x: x, y: y)
    }

    // MARK: - 09 · Predict future demand

    @MainActor static func predictDemand(_ t: Double) -> some View {
        let k = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let axis = Ease.easeInOut(Ease.clip(t, 0.8, 2.0))
        let youP = Ease.easeOutBack(Ease.clip(t, 1.8, 2.6))
        let sweep = Ease.easeInOut(Ease.clip(t, 3.0, 7.5))       // wave moves now → +10y
        let allP = Ease.easeOut(Ease.clip(t, 7.0, 8.0))
        let cap = Ease.easeOut(Ease.clip(t, 9.4, 10.6))
        let w: CGFloat = 1300
        return ZStack {
            kicker("YOUR NEEDS PREDICT FUTURE DEMAND", k)
                .frame(maxHeight: .infinity, alignment: .top).padding(.top, 130)
            VStack(spacing: 60) {
                ZStack {
                    Rectangle().fill(faint).frame(width: CGFloat(axis) * w, height: 3)
                        .frame(width: w, alignment: .leading)
                    // moving marker
                    Circle().fill(accent).frame(width: 28, height: 28)
                        .shadow(color: accent.opacity(0.8), radius: 14)
                        .offset(x: -w / 2 + CGFloat(sweep) * w)
                        .opacity(youP)
                    HStack {
                        endpointLabel("YOU & YOUR FRIENDS", "now", ink, youP)
                        Spacer()
                        endpointLabel("EVERYONE", "+10 years", gold, allP)
                    }
                    .frame(width: w + 320)
                    .offset(y: 70)
                }
                .frame(width: w, height: 140)
            }
            Text("build what you and your friends want")
                .font(.custom("Inter-Bold", size: 46)).foregroundStyle(accent)
                .opacity(cap)
                .frame(maxHeight: .infinity, alignment: .bottom).padding(.bottom, 120)
        }
    }

    @ViewBuilder static func endpointLabel(_ title: String, _ sub: String, _ color: Color, _ p: Double) -> some View {
        VStack(spacing: 6) {
            Text(title).font(.custom("Inter-Bold", size: 34)).foregroundStyle(color)
            Text(sub).font(.system(size: 22, design: .monospaced)).foregroundStyle(dim)
        }
        .opacity(p).scaleEffect(0.85 + 0.15 * p)
    }

    // MARK: - 10 · The best ideas sound lame

    @MainActor static func ideasSoundLame(_ t: Double) -> some View {
        let k = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let cards: [(String, String, String)] = [
            ("APPLE", "“a computer in every home?”", "now: $3T"),
            ("AIRBNB", "“sleep on a stranger's airbed?”", "we funded it anyway"),
            ("FACEBOOK", "“undergrads stalking each other?”", "billions of users"),
        ]
        let cap = Ease.easeOut(Ease.clip(t, 9.8, 11.0))
        return ZStack {
            kicker("THE BEST IDEAS SOUND LAME AT FIRST", k)
                .frame(maxHeight: .infinity, alignment: .top).padding(.top, 120)
            HStack(spacing: 36) {
                ForEach(0..<cards.count, id: \.self) { i in
                    let p = Ease.easeOutBack(Ease.clip(t, 1.0 + Double(i) * 0.5, 1.8 + Double(i) * 0.5))
                    let strike = Ease.easeInOut(Ease.clip(t, 4.0 + Double(i) * 0.5, 5.0 + Double(i) * 0.5))
                    lameCard(cards[i].0, cards[i].1, cards[i].2, strike)
                        .opacity(p).scaleEffect(0.85 + 0.15 * p).offset(y: (1 - p) * 50)
                }
            }
            Text("that's exactly what kept them undiscovered")
                .font(.custom("Inter-Medium", size: 38)).foregroundStyle(ink)
                .opacity(cap)
                .frame(maxHeight: .infinity, alignment: .bottom).padding(.bottom, 110)
        }
    }

    @ViewBuilder static func lameCard(_ name: String, _ doubt: String, _ outcome: String, _ strike: Double) -> some View {
        VStack(alignment: .leading, spacing: 22) {
            Text(name).font(.custom("Inter-Black", size: 46)).tracking(-1).foregroundStyle(ink)
            ZStack(alignment: .leading) {
                Text(doubt).font(.custom("Inter-Light", size: 28)).foregroundStyle(dim)
                    .fixedSize(horizontal: false, vertical: true).lineSpacing(5)
                Rectangle().fill(warn).frame(width: CGFloat(strike) * 360, height: 3)
            }
            Spacer(minLength: 0)
            HStack(spacing: 10) {
                Rectangle().fill(accent).frame(width: 16, height: 3)
                Text(outcome).font(.custom("Inter-Bold", size: 30)).foregroundStyle(accent)
            }
        }
        .padding(34)
        .frame(width: 470, height: 360, alignment: .topLeading)
        .background(RoundedRectangle(cornerRadius: 26, style: .continuous).fill(panel))
        .overlay(RoundedRectangle(cornerRadius: 26, style: .continuous).stroke(accent.opacity(0.28), lineWidth: 1.5))
    }

    // MARK: - 11 · Justin.TV → Twitch

    @MainActor static func twitch(_ t: Double) -> some View {
        let k = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let camP = Ease.easeOutBack(Ease.clip(t, 1.0, 2.0))
        let arrow = Ease.easeInOut(Ease.clip(t, 8.0, 9.0))
        let twitchP = Ease.easeOutBack(Ease.clip(t, 9.2, 10.4))
        let live = (sin(t * 5) > 0) ? 1.0 : 0.25
        let twitchColor = Color(red: 0.578, green: 0.353, blue: 0.969)   // twitch purple
        return ZStack {
            kicker("BUILD PROJECTS WITH FRIENDS", k)
                .frame(maxHeight: .infinity, alignment: .top).padding(.top, 130)
            HStack(spacing: 70) {
                VStack(spacing: 18) {
                    ZStack {
                        Circle().fill(panel).frame(width: 200, height: 200)
                            .overlay(Circle().stroke(faint, lineWidth: 2))
                        Image(systemName: "video.fill").font(.system(size: 76)).foregroundStyle(ink)
                        HStack(spacing: 8) {
                            Circle().fill(warn).frame(width: 12, height: 12).opacity(live)
                            Text("LIVE").font(.system(size: 18, weight: .heavy, design: .monospaced)).foregroundStyle(warn)
                        }
                        .offset(y: 130)
                    }
                    .scaleEffect(camP).opacity(camP)
                    Text("JUSTIN.TV")
                        .font(.system(size: 26, weight: .bold, design: .monospaced)).tracking(2)
                        .foregroundStyle(dim).opacity(camP)
                    Text("a guy streaming his life")
                        .font(.custom("Inter-Light", size: 24)).foregroundStyle(faint).opacity(camP)
                }
                Image(systemName: "arrow.right")
                    .font(.system(size: 60, weight: .bold)).foregroundStyle(accent)
                    .opacity(arrow).offset(x: (1 - arrow) * -30)
                Text("Twitch")
                    .font(.custom("Inter-Black", size: 130)).tracking(-3).foregroundStyle(twitchColor)
                    .opacity(twitchP).scaleEffect(0.7 + 0.3 * twitchP)
            }
            Text("you predict future demand — so \"random cool stuff\" isn't random")
                .font(.custom("Inter-Medium", size: 34)).foregroundStyle(ink)
                .opacity(Ease.easeOut(Ease.clip(t, 11.2, 12.4)))
                .frame(maxHeight: .infinity, alignment: .bottom).padding(.bottom, 110)
        }
    }

    // MARK: - 12 · Empathy, not exploitation

    @MainActor static func empathy(_ t: Double) -> some View {
        let k = Ease.easeOut(Ease.clip(t, 0.0, 0.7))
        let exP = Ease.easeOut(Ease.clip(t, 0.9, 1.7))
        let strike = Ease.easeInOut(Ease.clip(t, 2.4, 3.6))
        let empP = Ease.easeOutBack(Ease.clip(t, 4.0, 5.2))
        let cap = Ease.easeOut(Ease.clip(t, 7.0, 8.2))
        return ZStack {
            VStack(spacing: 30) {
                kicker("THE REAL KEY", k)
                ZStack {
                    Text("EXPLOITATION")
                        .font(.custom("Inter-Black", size: 96)).tracking(-2).foregroundStyle(dim.opacity(0.6))
                        .opacity(exP)
                    Rectangle().fill(warn).frame(width: CGFloat(strike) * 700, height: 8)
                }
                Text("EMPATHY")
                    .font(.custom("Inter-Black", size: 150)).tracking(-4).foregroundStyle(accent)
                    .opacity(empP).scaleEffect(0.8 + 0.2 * empP)
                Text("understand users so deeply you build exactly what they want")
                    .font(.custom("Inter-Light", size: 40)).foregroundStyle(ink)
                    .opacity(cap)
            }
        }
    }

    // MARK: - 13 · Lockup

    @MainActor static func lockup(_ t: Double) -> some View {
        let eq    = Ease.easeOutBack(Ease.clip(t, 0.3, 1.3))
        let arrow = Ease.easeInOut(Ease.clip(t, 1.6, 2.4))
        let dollarP = Ease.easeOutBack(Ease.clip(t, 2.4, 3.6))
        let sweep = Ease.easeInOut(Ease.clip(t, 3.6, 4.4))
        let sub   = Ease.easeOut(Ease.clip(t, 4.2, 5.2))
        let credit = Ease.easeOut(Ease.clip(t, 6.4, 7.6))
        return ZStack {
            VStack(spacing: 26) {
                Text("GROWTH  ×  TIME")
                    .font(.custom("Inter-Bold", size: 64)).tracking(2).foregroundStyle(dim)
                    .opacity(eq).scaleEffect(0.9 + 0.1 * eq)
                Image(systemName: "arrow.down")
                    .font(.system(size: 46, weight: .bold)).foregroundStyle(accent).opacity(arrow)
                Text("$1,000,000,000")
                    .font(.custom("Inter-Black", size: 110)).tracking(-3).foregroundStyle(gold)
                    .opacity(dollarP).scaleEffect(0.85 + 0.15 * dollarP)
                Rectangle().fill(accent).frame(width: CGFloat(sweep) * 760, height: 8)
                Text("make customers happy — you don't have to cheat.")
                    .font(.custom("Inter-Light", size: 46)).foregroundStyle(ink).opacity(sub)
                Text("after Paul Graham · rendered in Swift · swift-render")
                    .font(.system(size: 24, design: .monospaced)).foregroundStyle(faint)
                    .opacity(credit).padding(.top, 18)
            }
        }
    }
}
